# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del desarrollador')),
                ('fechaRegistro', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
                ('fechaMoficacion', models.DateTimeField(verbose_name='Fecha de modificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de historia de usuario')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion de la historia de usuario')),
                ('puntuacionGeneral', models.IntegerField(default=0, verbose_name='Puntuacion general')),
                ('fechaRegistro', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
                ('fechaMoficacion', models.DateTimeField(null=True, verbose_name='Fecha de modificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fechaInicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('fechaFinalizacion', models.DateTimeField(verbose_name='Fecha de finalizacion')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoAgil',
            fields=[
                ('proyecto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelosGenericos.Proyecto')),
                ('correspondenciaPuntosHoras', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Correspondencia puntos horas proyecto')),
            ],
            bases=('modelosGenericos.proyecto',),
        ),
        migrations.AddField(
            model_name='historia',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelosGenericos.Proyecto'),
        ),
    ]
