# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelosGenericos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desarrollador',
            name='horasDisponiblesSemana',
            field=models.IntegerField(default=0, verbose_name='Horas disponibles a la semana'),
        ),
    ]
