# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelosGenericos', '0002_desarrollador_horasdisponiblessemana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desarrollador',
            name='fechaMoficacion',
            field=models.DateTimeField(null=True, verbose_name='Fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFinalizacion',
            field=models.DateTimeField(null=True, verbose_name='Fecha de finalizacion'),
        ),
    ]
