# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mockupAppCompleta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del atributo')),
                ('descripcion', models.TextField(max_length=50, verbose_name='Descripcion del atributo')),
                ('fechaRegistro', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
            ],
        ),
        migrations.CreateModel(
            name='DesarrolladorAsignacion',
            fields=[
                ('desarrollador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mockupAppCompleta.Desarrollador')),
            ],
            bases=('mockupAppCompleta.desarrollador',),
        ),
        migrations.CreateModel(
            name='HistoriaAsignacion',
            fields=[
                ('historias_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mockupAppCompleta.Historias')),
            ],
            bases=('mockupAppCompleta.historias',),
        ),
        migrations.CreateModel(
            name='PuntuacionAtributoDesarrollador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Puntuacion')),
                ('fechaRegistro', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuacion_desarrollador', to='asignacionHistorias.Atributo')),
                ('desarrollador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuacion_desarrollador', to='asignacionHistorias.DesarrolladorAsignacion')),
            ],
        ),
        migrations.CreateModel(
            name='PuntuacionAtributoHistoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Puntuacion')),
                ('fechaRegistro', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuacion_historia', to='asignacionHistorias.Atributo')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuacion_historia', to='asignacionHistorias.HistoriaAsignacion')),
            ],
        ),
        migrations.AddField(
            model_name='historiaasignacion',
            name='atributos',
            field=models.ManyToManyField(related_name='HistoriarAsignacionAtributos', through='asignacionHistorias.PuntuacionAtributoHistoria', to='asignacionHistorias.Atributo'),
        ),
        migrations.AddField(
            model_name='desarrolladorasignacion',
            name='atributos',
            field=models.ManyToManyField(related_name='DesarrolladorAsignacionAtributos', through='asignacionHistorias.PuntuacionAtributoDesarrollador', to='asignacionHistorias.Atributo'),
        ),
    ]
