# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelosGenericos', '0003_auto_20180207_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionPorHoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion_horas_puntos', models.FloatField(verbose_name='Relacion horas-puntos')),
                ('fechaRegistro', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
            ],
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del atributo')),
                ('descripcion', models.TextField(max_length=50, verbose_name='Descripcion del atributo')),
                ('fechaRegistro', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
            ],
        ),
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.CharField(max_length=50, verbose_name='Id externo')),
                ('horasDisponiblesSemana', models.IntegerField(default=0, verbose_name='Horas disponibles a la semana')),
                ('fechaRegistro', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
                ('asignacion_por_horas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacionHistorias.AsignacionPorHoras')),
            ],
        ),
        migrations.CreateModel(
            name='DesarrolladorConAtributos',
            fields=[
                ('desarrollador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelosGenericos.Desarrollador')),
            ],
            bases=('modelosGenericos.desarrollador',),
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.IntegerField(verbose_name='Id Externo')),
                ('puntuacionGeneral', models.IntegerField(default=0, verbose_name='Puntuacion general')),
                ('fechaRegistro', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
                ('asignacion_por_horas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacionHistorias.AsignacionPorHoras')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaConAtributos',
            fields=[
                ('historia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelosGenericos.Historia')),
            ],
            bases=('modelosGenericos.historia',),
        ),
        migrations.CreateModel(
            name='PuntuacionAtributoDesarrollador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Puntuacion')),
                ('fechaRegistro', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuacion_desarrollador', to='asignacionHistorias.Atributo')),
                ('desarrollador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuacion_desarrollador', to='asignacionHistorias.DesarrolladorConAtributos')),
            ],
        ),
        migrations.CreateModel(
            name='PuntuacionAtributoHistoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Puntuacion')),
                ('fechaRegistro', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuacion_historia', to='asignacionHistorias.Atributo')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuacion_historia', to='asignacionHistorias.HistoriaConAtributos')),
            ],
        ),
        migrations.AddField(
            model_name='historiaconatributos',
            name='atributos',
            field=models.ManyToManyField(related_name='HistoriarAsignacionAtributos', through='asignacionHistorias.PuntuacionAtributoHistoria', to='asignacionHistorias.Atributo'),
        ),
        migrations.AddField(
            model_name='desarrolladorconatributos',
            name='atributos',
            field=models.ManyToManyField(related_name='DesarrolladorAsignacionAtributos', through='asignacionHistorias.PuntuacionAtributoDesarrollador', to='asignacionHistorias.Atributo'),
        ),
    ]
