# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del desarrollador')),
                ('fechaRegistro', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
                ('fechaMoficacion', models.DateTimeField(verbose_name='Fecha de modificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Historias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de historia de usuario')),
                ('puntuacionGeneral', models.IntegerField(default=0, verbose_name='Puntuación general')),
                ('fechaRegistro', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
                ('fechaMoficacion', models.DateTimeField(verbose_name='Fecha de modificacion')),
            ],
        ),
    ]
