# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Aplicación')),
                ('url', models.URLField(max_length=50, unique=True, verbose_name='URL de la Aplicación')),
                ('descripcion', models.TextField(max_length=50, verbose_name='Resumen de la aplicacion')),
                ('fechaRegistro', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
                ('fechaMoficacion', models.DateTimeField(null=True, verbose_name='Fecha de modificacion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.Usuario')),
            ],
        ),
    ]
